### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jpzk** [bitcoinfees/feesim#2]
Is there any documentation on how the model concretely works? Would be of big help. Thanks.

**Comment by bitcoinfees** [comment]
Sorry there isn't, except for a brief overview [here](https://bitcoinfees.github.io/about/). If you are familiar with how the Bitcoin network operates, that should be enough to give you a pretty good idea about how the program works. It doesn't talk about parameter estimation though.

**Comment by jpzk** [comment]
Okay, thanks for the quick response!
